{% set name = "tox-conda" %}
{% set version = "0.2.1" %}
{% set sha256 = "ee0a1c84aa2386ef92a85fba39b1578d0e464758b33becb2d1402b371a075c40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >3.3
    - pip
  run:
    - python >3.3
    - tox >=3.8.1

test:
  imports:
    - tox_conda.plugin

about:
  home: https://github.com/tox-dev/tox-conda
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Make tox cooperate with conda envs'
  doc_url: https://github.com/tox-dev/tox-conda
  dev_url: https://github.com/tox-dev/tox-conda

extra:
  recipe-maintainers:
    - njzjz
