{% set name = "tox-conda" %}
{% set version = "0.7.3" %}
{% set sha256 = "0500920fe710df5c69818540b9246a70737a66e3ac6834a7aa2a9c6e7d7a13c6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox_conda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - tox >=3.8.1

test:
  imports:
    - tox_conda.plugin

about:
  home: https://github.com/tox-dev/tox-conda
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tox plugin that provides integration with conda
  doc_url: https://github.com/tox-dev/tox-conda
  dev_url: https://github.com/tox-dev/tox-conda

extra:
  recipe-maintainers:
    - njzjz
    - ickc
