travis:
  secure:
    BINSTAR_TOKEN: YnyabYmQmBPlX0BkgQmtBtsubAiUzk+unUEyhZ8I0cQrGuXI8DYUyr67fR8yt+JcUUhpa3y7+EoZYgbCvISYQNKrO5Kvq4PDbNNseI+wTExgSbG3NTxA9P6x9HYS/b3+Piu9RuRnyPwxSnx/RDbRcLjEvcI6pMSGFsTwrc3P9wak6Cy7blVzSNOwC0SfqtMgoTom3YRcTEoIoyhHLF+E3xmPM3j9MI7ExwBV0nQE25Z5ttsHK0ejnFwgHvIhhPW8GFzOz7kOp01kzT6MxWQiCN3PNy2TliukzAIAlnu1A9C8wlpX3R8Xl6G6seKbANOwb6E7x5zZQGsZmt2mF2l8AY0lnIs37Uc3ePZKgj16jw4eJzbkMA4eEXYdB8wuKVSxKE6Qigpqwe5H4tyuOx1Wj1NZeHAu9LekAZ08SH28jk3q5mC13hf4xLXfUbcOo5+hZn3ld4vz2Wh4YEHEEzn+SpxqFuMBDGq79W6SpLLEFuZj88Sp9dGjg6GhisFV6bMogluovyRFmXUOwyQNPfKhh9eFDgee1ZYIrbkSv7RL8iBjZ3T2oMIVx12ekyKv5S50mboMIKF8+HtebW5YarmPz0DtQAPWldkr/ESAED2Q22LLj5AZZw6DqmZlduQBVgHTKVQbQtrF8y4w+4VWJVhDrau9scoB9uPLWkpIH3qDz2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
